name: swuConomy
version: 1.1
authors: [SwuCraft Collaboration, CptFinn, Duckapple]
main: com.swucraft.swuConomy.Main
api-version: 1.15
commands:
  balance:
    description: SwuConomy balance
    usage: /balance
permissions:
  swuConomy.admin:
    description: Can modify signs
  swuConomy.user:
    description: Can access usable signs